#!/usr/bin/env python3
"""
ARP v3 Drug Discovery Pipeline

Complete workflow:
1. Target identification (from research topic)
2. Literature survey (ARP agents)
3. Peptide generation (ACP-Diffusion concept)
4. Structure prediction (AlphaFold2)
5. ADMET analysis
6. Ranking and selection

Usage:
    python3 discovery_pipeline.py "SIRT3 mitophagy activators for sarcopenia"
"""

import sys
import json
from datetime import datetime
from pathlib import Path

# Add data module to path
sys.path.insert(0, str(Path(__file__).parent))

from data.peptgene import (
    PeptideGenerator,
    TARGET_DATABASE,
    get_targets_for_research,
)

def print_banner(text: str):
    print(f"\n{'='*60}")
    print(f"  {text}")
    print(f"{'='*60}\n")

def main(topic: str):
    print_banner(f"ARP v3 Drug Discovery — {topic}")
    
    # Step 1: Target Identification
    print("[STEP 1] Target Identification...")
    targets = get_targets_for_research(topic)
    print(f"  Identified targets: {', '.join(targets)}")
    
    for target in targets:
        if target in TARGET_DATABASE:
            info = TARGET_DATABASE[target]
            print(f"\n  {target}:")
            print(f"    Pathway: {info['pathway']}")
            print(f"    Function: {info['function']}")
            print(f"    Priority: {info['priority']}")
    
    # Step 2: Peptide Generation
    print_banner("STEP 2: Peptide Generation (ACP-Diffusion)")
    generator = PeptideGenerator()
    
    all_candidates = []
    for target in targets:
        print(f"\n  Generating candidates for {target}...")
        candidates = generator.generate(target, num_sequences=5)
        
        for i, c in enumerate(candidates, 1):
            print(f"    {i}. {c.sequence} (conf={c.confidence:.2f})")
            print(f"       {c.notes}")
            all_candidates.append(c)
    
    # Step 3: Validation
    print_banner("STEP 3: Sequence Validation")
    validated = []
    for c in all_candidates:
        props = generator.validate_sequence(c.sequence)
        mods = generator.suggest_modifications(c.sequence)
        
        print(f"\n  {c.sequence} ({c.target}):")
        print(f"    Length: {props['length']}")
        print(f"    Hydrophobicity: {props['hydrophobicity']:.2f}")
        print(f"    Net charge: {props['net_charge']:.2f}")
        print(f"    Modifications suggested: {len(mods)}")
        
        if props['is_valid'] and 8 <= props['length'] <= 30:
            validated.append(c)
    
    # Step 4: Ranking
    print_banner("STEP 4: Candidate Ranking")
    
    # Sort by confidence
    ranked = sorted(validated, key=lambda x: x.confidence, reverse=True)
    
    print("\n  Top Candidates:")
    for i, c in enumerate(ranked[:5], 1):
        print(f"\n  Rank {i}: {c.sequence}")
        print(f"    Target: {c.target}")
        print(f"    Confidence: {c.confidence:.2f}")
        print(f"    Method: {c.generation_method}")
        print(f"    Notes: {c.notes}")
    
    # Step 5: Save Report
    print_banner("STEP 5: Generate Report")
    
    report = f"""# ARP v3 Drug Discovery Report

## Topic: {topic}
## Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}

---

## Targets Identified

| Target | Pathway | Function | Priority |
|--------|---------|---------|----------|
"""
    
    for target in targets:
        if target in TARGET_DATABASE:
            info = TARGET_DATABASE[target]
            report += f"| {target} | {info['pathway']} | {info['function']} | {info['priority']} |\n"
    
    report += f"""
## Candidates Generated

| Rank | Sequence | Target | Confidence | Method |
|------|----------|--------|------------|--------|
"""
    
    for i, c in enumerate(ranked[:10], 1):
        report += f"| {i} | {c.sequence} | {c.target} | {c.confidence:.2f} | {c.generation_method} |\n"
    
    report += """
## Next Steps

1. **Experimental validation** — Synthesize top candidates
2. **Binding assays** — SPR, ITC for target confirmation
3. **Cellular activity** — MTT, Caspase assays
4. **In vivo validation** — Mouse models
5. **ADMET** — Pharmacokinetics profiling

---

*Generated by ARP v3 Drug Discovery Pipeline*
"""
    
    # Save report
    slug = '-'.join(topic.split()[:3]).lower()
    out_path = Path(f"outputs/drug-discovery-{slug}")
    out_path.mkdir(parents=True, exist_ok=True)
    
    report_file = out_path / "discovery-report.md"
    report_file.write_text(report)
    
    print(f"\n  Report saved: {report_file}")
    print(f"\n{'='*60}")
    print(f"✅ Drug Discovery Complete!")
    print(f"{'='*60}\n")
    
    return {
        "targets": targets,
        "candidates": len(ranked),
        "report": str(report_file)
    }

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 discovery_pipeline.py <research topic>")
        print("Example: python3 discovery_pipeline.py 'SIRT3 mitophagy sarcopenia'")
        sys.exit(1)
    
    topic = " ".join(sys.argv[1:])
    result = main(topic)
    print(f"\nResults: {result['candidates']} candidates, report at {result['report']}")
